config/routes.rb
Rails.application.routes.draw do
  get    '/',        to: 'sessions#new', as: 'root'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/dashboard',  to: 'users#show'
  post 'admin/notification' => 'admin/notification#create'


  namespace :admin do
    get '/dashboard' => :index
    resources :users, only: [:new, :create, :index, :show]
    resources :interviews, only: [:index, :show, :new, :create, :edit, :update]
    resources :candidates, only: [:index, :show, :new, :create]
    resources :competencies
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :interviews, only: [:edit, :update, :index]
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :interviews
  accepts_nested_attributes_for :interviews

  validates :first_name, :last_name, :target_role, presence: true
end

app/controllers/admin/candidates_controller.rb
class Admin::CandidatesController <ApplicationController
  before_action :require_admin

  def index
    @candidates = Candidate.all
  end

  def show
    @candidate = Candidate.find(params[:id])
  end

  def new
    @candidate = Candidate.new
  end

  def create
    candidate = Candidate.new(candidate_params)

    if candidate.save
      flash[:success] = "Created a new candidate for #{candidate.target_role}"
      redirect_to admin_candidates_path
    else
      render :new
      flash[:danger] = "Try again! Information is wrong."
    end
  end

  private

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :target_role)
  end

end

app/views/admin/candidates/index.html.erb
<div class="container">
<h4> Current Candidates: </h4>
  <% @candidates.each do |candidate| %>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to "Show Details for Upcoming Interviews", admin_candidate_path(candidate.id) %> </li>
    <li class="list-group-item"> <strong>Candidate:</strong> <%= candidate.first_name %> <%= candidate.last_name %></li>
    <li class="list-group-item"> <strong>Role:</strong> <%= candidate.target_role %> </li> <br>
    </ul>
  <%end %>
  <a href="/admin/candidates/new" class="btn btn-primary btn-lg primary" role="button" aria-disabled="true">Create a New Candidate</a>
</div>

app/views/admin/candidates/new.html.erb
<h4> Add a New Candidate: </h4>
<div class="container">
<%= form_for ([:admin, @candidate]), :html => {:class => "form-horizontal center"} do |f| %>
<div class="form-group">
  <%= f.label :first_name, "First Name:", class: "col-md-4 control-label" %>
  <div class="col-md-4">
    <%= f.text_field :first_name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :last_name, "Last Name:", class: "col-md-4 control-label" %>
  <div class="col-md-4">
    <%= f.text_field :last_name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :target_role, "Targeted Role:", class: "col-md-4 control-label" %>
  <div class="col-md-4">
    <%= f.text_field :target_role, class: "form-control" %>
  </div>
</div>

<%= f.submit "Submit", class: "btn btn-primary btn-lg primary" %>
<% end %>
</div>

app/views/admin/candidates/show.html.erb
<div class="container">
<div class="card">
<h4 class="card-title"> <strong>Candidate Name: </strong> <%=@candidate.first_name%> <%=@candidate.last_name%></h4>
<h5 class="card-text"> <strong>Target Role </strong> <%=@candidate.target_role%> </h5>

  <div class="card-body">
<h5> All Interviews: </h5>
<% @candidate.interviews.map do |interview| %>
  <ul class="list-group">
  <li class="list-group-item"> <strong>Interview Date: </strong><%=interview.date.strftime('%b. %d, %Y')%> </li>
  <li class="list-group-item"> <strong>Status: </strong><%=interview.status.capitalize%> </li>
  <li class="list-group-item"> <strong>Interviewers: </strong><%=interview.user.first_name%> <%=interview.user.last_name%></li> <br>
</ul>
<%end%>
</div>
</div>