config/routes.rb
Rails.application.routes.draw do
  get    '/',        to: 'sessions#new', as: 'root'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/dashboard',  to: 'users#show'
  post 'admin/notification' => 'admin/notification#create'


  namespace :admin do
    get '/dashboard' => :index
    resources :users, only: [:new, :create, :index, :show]
    resources :interviews, only: [:index, :show, :new, :create, :edit, :update]
    resources :candidates, only: [:index, :show, :new, :create]
    resources :competencies
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :interviews, only: [:edit, :update, :index]
end

app/views/admin/index.html.erb
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active" href="#">Manage unTilt Application</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/admin/users">Manage Interviewers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/admin/interviews">Manage Interviews</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/admin/candidates">Manage Candidates</a>
        </li>
      </ul>
    </div>

  <h4 class="card-title">Welcome, <%= current_user.first_name %></h4>
  <h5> Company's Core Competencies: </h5>

    <% @competencies.each do |competency| %>
    <div class="card-deck">
    <div class= "card p-3 text-left">
        <div class="card-block">
          <h6 class="card-title"> <strong>Name:</strong> <%=competency.name%></h6>
          <h6 class="card-text"><strong>Description:</strong> <%=competency.description%> </h6>
      <a ><%= link_to "Edit", edit_admin_competency_path(competency) %></a>
      <a ><%= link_to "Delete", admin_competency_path(competency), method: :delete, data: { confirm: "Are you sure?" } %> </a><br>
      </div>
    </div>
      </div>
    <%end%>
    <div class="card-footer">
  <%= button_to "Create a New Competency", new_admin_competency_path, method: :get, class: "btn btn-primary"%><br>
  <%= button_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary", id:'admin-logout'%>
</div>
</div>