config/routes.rb
Rails.application.routes.draw do
  get    '/',        to: 'sessions#new', as: 'root'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/dashboard',  to: 'users#show'
  post 'admin/notification' => 'admin/notification#create'


  namespace :admin do
    get '/dashboard' => :index
    resources :users, only: [:new, :create, :index, :show]
    resources :interviews, only: [:index, :show, :new, :create, :edit, :update]
    resources :candidates, only: [:index, :show, :new, :create]
    resources :competencies
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :interviews, only: [:edit, :update, :index]
end

app/controllers/admin/interviews_controller.rb
class Admin::InterviewsController <ApplicationController
  before_action :require_admin
  def index
    @interviews = Interview.includes(:user, :candidate)

  end

  def show
    @interview = Interview.find(params[:id])
  end

  def new
    @interviewers_options = User.all.map{ |u| [ u.first_name, u.id ] }
    @candidates_options = Candidate.all.map{ |u| [ u.first_name, u.id ] }
    @competencies = Competency.includes(:questions)
    @interview = Interview.new
    competency = @interview.competencies.build
    competency.questions.build
  end

  def create

    interview = Interview.new(interview_params)
    interview.status = 0
    interviewer = User.find_by(params[:user_id])

    InterviewNotifierMailer.inform(interviewer, interview, interviewer.email).deliver_now
    flash[:notice] = "Successfully sent request to interviewer for upcoming interview."
    if interview.save
      flash[:success] = "Created a new for the following date: #{interview.date}"
      redirect_to admin_interviews_path
    else
      render :new
      flash[:danger] = "Try again! Information is wrong."
    end
  end

  def edit
    @interview = Interview.find(params[:id])
    @interviewers_options = User.all.map{ |u| [ u.first_name, u.id ] }
  end

  def update
    interview = Interview.find(params[:id])
    interview.update(interview_params)

    flash[:success] = "Updated the interview for the following candidate: #{interview.candidate.first_name}"
    redirect_to admin_interviews_path
  end

  private
    def interview_params
      params.require(:interview).permit(:date, :user_id, :candidate_id, :status, :competencies => [:id, :name, :questions => [:id]])
    end




end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController

  def index
    @interviews = current_user.interviews.open

  end

  def edit
    @interview = Interview.find(params[:id])
    competency = @interview.competencies.build
    competency.interview_competencies.build
    @interview.interview_questions.build
    @questions = Question.all.map{ |u| [ u.question, u.id ] }
  end

  def update
    interview = Interview.find(params[:id])
    interview.update(interview_params)
    interview.status = 1

    score_params[:interview_competencies_attributes].each do |interview_competency|
      interview_score = InterviewCompetency.find(score_params[:interview_competencies_attributes][interview_competency][:id])
      interview_score.competency_score = score_params[:interview_competencies_attributes][interview_competency][:competency_score]
    end

    flash[:success] = "Thanks for completing the interview!"

    redirect_to interviews_path

  end

 private
    def interview_params
      params.require(:interview).permit(:score, :comment)
    end

    def score_params
      params.require(:interview).permit(interview_competencies_attributes: [:competency_score, :id])
    end
end

app/views/admin/interviews/edit.html.erb
<h4> Update Date or Interviewer Below: </h4>
<div class="container">
<%= form_for ([:admin, @interview]), :html => {:class => "form-horizontal center"} do |f| %>
<div class="form-group">
  <%= f.label :date, "Interview Date:", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.date_field :date, class: "form-control" %>
  </div>
</div>
<div class="form-group">
  <%= f.label :Status, "Update the Status", class: "col-md-4 control-label" %>
  <div class="col-md-8">
  <%= f.text_field :status, class: "form-control" %>
</div>
</div>
<div class="form-group">
  <%= f.label :interview_id, class: "col-md-4 control-label" %>
    <div class="col-md-8">
  <%= f.select(:user_id,   @interviewers_options) %>
</div>
</div>
<%= f.submit "Submit", class: "btn  btn-primary btn-lg  btn-primary" %>
<% end %>
</div>

app/views/admin/interviews/index.html.erb
<div class="container">
<h4> All Open and Completed Interviews: </h4>
  <% @interviews.each do |interview| %>
    <ul class="list-group">
    <li class="list-group-item"> <%= link_to "Show Details", admin_interview_path(interview.id) %> </li>
    <li class="list-group-item"> <strong>Candidate:</strong> <%= interview.candidate.first_name %> <%= interview.candidate.last_name %></li>
    <li class="list-group-item"> <strong>Date: </strong><%= interview.date.strftime('%b. %d, %Y') %> </li>
    <li class="list-group-item"> <strong>Role:</strong> <%= interview.candidate.target_role %> </li>
    <li class="list-group-item"> <strong>Interviewer:</strong> <%= interview.user.first_name %> <%= interview.user.last_name %></li>
    <li class="list-group-item"> <strong>Status: </strong> <%= interview.status.capitalize %> </li> <br>
    </ul>
  <%end %>

  <a href="/admin/interviews/new" class="btn btn-primary btn-lg primary" role="button" aria-disabled="true">Create a New Interview</a>
</div>

app/views/admin/interviews/new.html.erb
<h4> Schedule a New Interview</h4>
<div class="container">
<%= form_for ([:admin, @interview]), :html => {:class => "form-horizontal center"} do |f| %>

<div class="form-group">
  <%= f.label :date, "Interview Date:", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.date_field :date, class: "form-control" %>
  </div>
</div>

<div class="form-group">
<div class="field">
  <%= f.label :candidate_id , class: "col-md-4 control-label"%>
  <%= f.select(:candidate_id,   @candidates_options) %>
</div>
</div>

<div class="form-group">
<div class="field">
  <%= f.label :interview_id , class: "col-md-4 control-label"%>
  <%= f.select(:user_id,   @interviewers_options) %>
</div>
</div>

<div class="form-group">
  <h6> Select up to 3 competency and a question for the interview. </h6>
  <div class="checkbox" id="competencies_id">
    <ul>
  <% @competencies.each_with_index do |competency, index| %>
      <li>
        <%= f.fields_for :competencies, index: index do |fm| %>
        <%= fm.hidden_field :name, value: competency.name, id: "#{competency.name}"  %>
        <%= fm.label :name, value: competency.name, id: "#{competency.name}"%>
        <%= fm.check_box :id, {}, competency.id %>
        <% competency.questions.each_with_index do |question, another_index| %>

          <%= fm.fields_for :questions, index: another_index do |ft| %>
          <ul>
            <%= ft.hidden_field :question, value: question.question %>
            <%= ft.label :question, value: question.question, id: "#{question.id}" %>
            <%= ft.check_box :id, {}, question.id %>
          </ul>
          <%end%>
        <%end%>
      <% end %>
    </li>
  <%end%>
</ul>
</div>
</div>
<div class="form-group">
<%= f.submit "Submit", class: "btn  btn-primary btn-lg  btn-primary" %>
<% end %>
</div>
</div>

app/views/admin/interviews/show.html.erb
<div class="container">
<div class="card">
<h4 class="card-title"> Details for the Interview scheduled on <%=@interview.date.strftime('%b. %d, %Y') %> </h4>
<h6 class="card-text"> <strong>Candidate:</strong> <%=@interview.candidate.first_name%> <%=@interview.candidate.last_name%></h6>
<h6 class="card-text"> <strong>Interviewer:</strong> <%=@interview.user.first_name%> <%=@interview.user.last_name%></h6>
<h6 class="card-text"> <strong>Status: </strong> <%=@interview.status.capitalize%> </p>
<p><%= link_to "Edit", edit_admin_interview_path(@interview), class: "btn btn-primary" %></p>
<div class="card-body">
  <h5> Target Role and Competencies </h5>
  <p class="card-text"> <strong>Role:</strong> <%=@interview.candidate.target_role%> </p>
 <%@interview.competencies.each do |competency| %>
  <ul class="list-group">
 <li class="list-group-item"> <strong>Competency:</strong> <%=competency.name%> </li>
 <li class="list-group-item"> <strong>Description: </strong><%=competency.description%> </li> <br>
 <%end %>
</ul>
</div>
</div>