config/routes.rb
Rails.application.routes.draw do
  get    '/',        to: 'sessions#new', as: 'root'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/dashboard',  to: 'users#show'
  post 'admin/notification' => 'admin/notification#create'


  namespace :admin do
    get '/dashboard' => :index
    resources :users, only: [:new, :create, :index, :show]
    resources :interviews, only: [:index, :show, :new, :create, :edit, :update]
    resources :candidates, only: [:index, :show, :new, :create]
    resources :competencies
  end

  resources :users, only: [:new, :create, :edit, :update]
  resources :interviews, only: [:edit, :update, :index]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :interviews

  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, :job_title, :department, :password, presence: true

  enum role: ["interviewer", "admin"]
  enum gender: ["male", "female", "transgender_female", "transgender_male", "gender_variant"]
  enum race: ["white", "black", "American_Indian", "Asian", "Native_Hawaiian"]
  enum education_level: ["high_school", "associate", "bachelor", "master", "doctoral"]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController <ApplicationController
  before_action :require_admin
  def new
    @user = User.new

  end

  def create
    @user = User.new(user_params)
    @user.role = 0
    if @user.save
      flash[:success] = "Created a new #{@user.first_name}"
      redirect_to admin_users_path

    else
      render :new
      flash[:danger] = "Try again! Information is wrong."
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :job_title, :department)
  end

end

app/controllers/users_controller.rb
class UsersController <ApplicationController
  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.role = 1
    if @user.save
      flash[:success] = "Welcome #{@user.email}"
      session[:user_id] = @user.id
      redirect_to admin_dashboard_path
    else
      render :new
      flash[:danger] = "Try again! Information is wrong."
    end
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to dashboard_path
  end
  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :job_title, :department, :password)
  end
end

app/views/admin/users/index.html.erb
<div class="container">
<h4> Availble Interviewers </h4>
  <% @users.each do |user| %>
  <ul class="list-group">
    <li class="list-group-item"> <strong>Name:</strong> <%= user.first_name %> <%= user.last_name %> </li>
    <li class="list-group-item"> <strong>Email:</strong> <%= link_to "#{user.email}", admin_user_path(user) %> </li>
    <li class="list-group-item"><strong> Job Title:</strong> <%= user.job_title %> </li>
    <li class="list-group-item"> <strong>Department: </strong><%= user.department %> </li><br>
    </ul>
  <%end %>
  <a href="/admin/users/new" class="btn btn-primary btn-lg primary" role="button" aria-disabled="true">Add a New Interviewer</a>
</div>

app/views/admin/users/new.html.erb
<h4> Add a New Interviewer to the Application</h4>
<div class="container">
<%= form_for ([:admin, @user]), :html => {:class => "form-horizontal center"} do |f| %>

      <div class="form-group">
        <%= f.label :first_name, "First name:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, "Last name:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "Email:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Password:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :job_title, "Job Title:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :job_title, class: "form-control" %>
        </div>
      </div>

        <div class="form-group">
          <%= f.label :department, "Department:", class: "col-md-4 control-label" %>
          <div class="col-md-8">
            <%= f.text_field :department, class: "form-control" %>
          </div>
        </div>

      <%= f.submit "Submit", class: "btn btn-primary btn-lg primary" %>
 <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
<div class="card w-75">
  <h3 class="card-header">Details for Interviewer:<%=@user.first_name %> <%= @user.last_name %></h3>
  <div class="card-block">
    <p class="card-text"><strong>Job Title:</strong> <%=@user.job_title%></p>
    <p class="card-text"><strong>Department: </strong><%=@user.department%></p>
    <p class="card-text"><strong>Email:</strong> <%=@user.email%></p>
  </div>
</div>
</div>